apiVersion: apps/v1
kind: Deployment
metadata:
  name: wot-dash-lab-server-deployment
  labels:
    app.kubernetes.io/name: wot-dash-lab-server-deployment
    app.kubernetes.io/part-of: wot-dash-lab
    app: wot-dash-lab-server
    appType: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wot-dash-lab-server
  template:
    metadata:
      labels:
        app: wot-dash-lab-server
    spec:
      containers:
        - name: wot-dash-lab-server
          image: skimlik/wotdashlabserver:latest-dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - containerPort: 80