apiVersion: v1
kind: Service
metadata:
  name: wot-dash-lab-server
  labels:
    app: wot-dash-lab-server
spec:
  ports:
    - port: 4283
      targetPort: 80
  selector:
    app: wot-dash-lab-server
  type: LoadBalancer